### ISSUE TITLE
Support Singelton Components Collection as ModuleStrategy

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Framework#10]
In the current platform the following feature is missing:

If a module provides a configurable plugin api for singelton components each component have to be added and configured manually by the maintenance.

There exists an attribute for normal plugins to set a global "ModuleStrategy". This attribute should be extended to define a collection strategy.

Sample Usage: The Maintenance Module provides a set of WCF endpoints which have to be configured. Some plugins are provided by other layers (e.G. MaintenanceWeb (HTML Maintenance) Plugin). To add this plugin to the Module, we need a UI. But how to add this plugin? Currently a workaround is implemented (see Marvin.Runtime.Maintenance.ModuleController)

**Comment by 1nf0rmagician** [comment]
We decided not to follow up on this feature request because of limited resources and business value. If in the future there is someone who wants to assist us in providing this feature we are happy to reopen it 😊
