### ISSUE TITLE
Set keep alive in TcpTransmission throws PlatformNotSupportedException on Linux/OSX

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Framework#100]
**Describe the bug**
The TcpTransmission throws a PlatformNotSupportedException when using IOControl to set keepAlive on non windows os.
That's because it's only supported on Windows. This IOControl code value is Windows-specific.

https://github.com/dotnet/runtime/issues/25555

This creates also an compiler warning `'IOControlCode.KeepAliveValues' is supported on 'windows'`

**Comment by 1nf0rmagician** [comment]
[Here](https://github.com/dotnet/runtime/issues/25555#issuecomment-689476572) is a discussion on that topic from the dotnet runtime repo with some hints to solve this issue

Also [here](https://github.com/PHOENIXCONTACT/MORYX-Core/blob/7b2ddd2bf56708527a1db7fcb809ada156eac98a/src/Moryx/Communication/Sockets/TcpTransmission.cs#L85) is a link to the specific line to be adapted.

**Comment by 1nf0rmagician** [comment]
And `Console.Beep(int, int)` is only supported on Windows as well with no signs for a linux implementation coming as the discussion [here](https://github.com/dotnet/runtime/issues/24366) indicates

**Comment by Toxantron** [comment]
Closed by #102
