### ISSUE TITLE
Publish documentation on moryx-industry.net

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Framework#21]
Currently the documentation is only generated. For releases it should also be published on moryx-industry.net.

**Comment by Toxantron** [comment]
So I had a look at https://github.com/dotnet/docs and they do use path links as well. Their documentation completely works on Github, you can event step through previous and next in the tutorials. Look at the [documentation for delegates](https://github.com/dotnet/docs/blob/master/docs/csharp/delegate-class.md) for example.

Inline examples are broken, but still link to the correct file, see [here](https://github.com/dotnet/docs/blob/master/docs/csharp/delegates-patterns.md#building-a-second-output-engine)

We should have hosted documentation, but that looks like working documentation is common on GitHub. We can also link to files using their path. I doubt the path changes more often than the namespace. Thoughts?
