### ISSUE TITLE
Can't use PluginConfigs Attribute inside of resources (asp.net core)

### ISSUE THREAD

**Issue by 1nf0rmagician** [PHOENIXCONTACT/MORYX-Framework#230]
**Describe the bug**
Can't use configured strategies inside of resources using the asp.net core endpoints instead of WCF.
When using the PluginConfigs Attribute on a property in your resource, a NotImplemented Exception will be thrown when the resource is created.

**To Reproduce**

Create a resource inside of an asp.net core project
Add a PluginConfigs Attribute to it
Run the program and create an instance of the resource via the Resource UI
See the NotImplementedException being thrown.
Expected behavior
The resource is succesfully created and displayed inside the UI with selectable configs as properties

**Screenshots**

**Environment:**

OS: Windows10
Version 5.13.3
Additional context
The culprit here appears to be ´Moryx.AbstractionLayer.Resources.Endpoints/ResourceSerialization.cs´ that provides the serialization with a mock container.

*Originally reported by @andreniggemann in https://github.com/PHOENIXCONTACT/MORYX-AbstractionLayer/issues/215*

**Comment by Toxantron** [comment]
Solved by #249
