### ISSUE TITLE
Usage of strategies in resources throws exception and make the resource unusable

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Framework#247]
**Describe the bug**
If you instantiate a resource for example the `BinaryConnectionConfig`, the UI cannot open this resource because the entry serialization fails. After investigation, if found out that the `ResourceSerialization` uses a `ContainerMock` to fill the possible values. The `ContainerMock` does not represent the container of the `ResourceManagement` where the strategies are known. 

**Expected behavior**
Available strategies are serializable and selectable on UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/920832/228247613-36cf793a-2e81-4e37-9c7d-c237b42e4996.png)

**Comment by Toxantron** [comment]
Fixed by #249
