### ISSUE TITLE
Moryx.Model console commands

### ISSUE THREAD

**Issue by Toxantron** [PHOENIXCONTACT/MORYX-Framework#25]
**Is your feature request related to a problem? Please describe.**
The MaintenanceWeb is an external repository and optional package, but is the only practical way to configure and create databases. 

**Describe the solution you'd like**
Especially for newbies and tutorials I expcect that **everything** possible on the Maintenance should be possible in the console.

**Describe alternatives you've considered**

**Additional context**

**Comment by 1nf0rmagician** [comment]
There is no console anymore
