### ISSUE TITLE
 Simplify Logging Structure

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Framework#8]
Entry Points:

- Reduce number of abstractions
- Replace reference to log queue from logger
- No "Internal Log", log4net could be hidden within LoggerManagement without any additional abstractions
- Remove logger configuration
- Replace `IModuleLogger` with `ILogger` -> maybe own implementation with child support and hierachies 
- Remove logging thread

**Comment by 1nf0rmagician** [comment]
Done
